Words attached to links
LearnWeb3DAO/Sophomore-Track pull request #13
Opened 2022-09-27 09:53 UTC by shikhar360

Some words were not attached to their respective links .

2022-10-04 16:12 UTC, shikhar360 commented
@haardikk21 😅 This as well

2022-10-04 16:35 UTC, haardikk21 requested changes

2022-10-04 16:35 UTC, haardikk21 commented on Decentralized-Exchange.md
> -Now lets install Web3Modal library(https://github.com/Web3Modal/web3modal). Web3Modal is an easy-to-use library to help developers add support for multiple providers in their apps with a simple custo
Arkane is right here, not Arcana. Arcana is not a wallet.

2022-10-04 16:35 UTC, haardikk21 commented on Initial-Coin-Offering.md
> +  await deployedCryptoDevsTokenContract.deployed();
Nice

2022-10-05 14:15 UTC, shikhar360 commented
@haardikk21 do review ser 😊

2022-11-24 16:48 UTC, yanukadeneth99 commented
Looks good. Nice work @shikhar360

2022-11-24 16:48 UTC, merged