Update What-is-Gas.md Regarding the ETH 2.0 or Eth2 misnomer.
LearnWeb3DAO/Sophomore-Track pull request #8
Opened 2022-09-21 22:25 UTC by RV12R

As the roadmap for Ethereum has evolved, Ethereum 2.0 has become an inaccurate representation of Ethereum’s roadmap. It is also misrepresented by some as Etheruem after the merge.This is clarified in their [official blog](https://blog.ethereum.org/2022/01/24/the-great-eth2-renaming).

2022-09-23 10:51 UTC, RV12R commented
Changing "What-is-Mining" to Before the merge and After the Merge (EIP 3675) can be done. Comment on this

2022-11-17 11:07 UTC, yanukadeneth99 approved these changes

2022-11-17 11:07 UTC, yanukadeneth99 commented on What-is-Mining.md
> +> [Ethereum Merge](https://ethereum.org/en/upgrades/merge/) (The Merge was executed on September 15, 2022) it replaced Proof of Work with Proof of Stake, which significantly changed how new blocks ar
Nice!

2022-11-26 18:27 UTC, yanukadeneth99 requested changes

2022-11-26 18:55 UTC, RV12R commented
Changes made check it out

2022-11-27 15:21 UTC, yanukadeneth99 commented
Hey @RV12R, great change! Thank you.

2022-11-27 15:22 UTC, merged